import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Explicit sidebar (not autogenerated) so ordering and grouping are intentional
// and match the wiki's narrative: start → architecture → backend → features →
// flows → operations.
const sidebars: SidebarsConfig = {
  wiki: [
    'overview',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/repo-tour', 'getting-started/local-dev'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/system',
        'architecture/stack-decisions',
        'architecture/frontend-mobile',
        'architecture/frontend-web',
        'architecture/service-layer',
      ],
    },
    {
      type: 'category',
      label: 'Data & backend',
      items: [
        'backend/data-model',
        'backend/security-rls',
        'backend/atomic-functions',
        'backend/edge-functions',
        'backend/migrations',
      ],
    },
    {
      type: 'category',
      label: 'Feature guides',
      items: [
        'features/chores',
        'features/rewards',
        'features/points-wallet',
        'features/reading',
        'features/savings-interest',
        'features/schedule',
        'features/auth-onboarding',
      ],
    },
    {
      type: 'category',
      label: 'End-to-end flows',
      items: [
        'flows/chore-approval',
        'flows/reward-purchase',
        'flows/reading-streak',
        'flows/savings-interest',
        'flows/kid-provisioning-auth',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['operations/ops', 'operations/ci-cd', 'operations/roadmap'],
    },
    'contributing',
  ],
};

export default sidebars;
