// Recurring-chore recurrence matching (task #14).
//
// LootLoop chores carry an optional iCal RRULE string (chores.recurrence_rule).
// The recurring-chore generator (the generate-recurring-chores Edge Function)
// materializes a chore_instances row for each active recurring chore whose rule
// "occurs on" a given date. This module is the pure, well-tested decision: does
// `rule` produce an occurrence on `date`?
//
// SUPPORTED RRULE SUBSET (deliberately minimal — NOT a full RFC 5545 engine):
//   * FREQ=DAILY
//       -> occurs every day.
//   * FREQ=WEEKLY;BYDAY=MO,WE,FR
//       -> occurs only on the listed weekdays. BYDAY tokens are the two-letter
//          iCal codes: MO TU WE TH FR SA SU. Omitting BYDAY on a WEEKLY rule
//          means "every day this week" -> treated as every day (every weekday).
//   * null / "" / whitespace-only
//       -> does NOT recur. One-off chores (recurrence_rule IS NULL) are owned by
//          a different flow and are NOT generated by this job.
//
// NOT supported (will return false rather than guess): FREQ=MONTHLY/YEARLY,
// INTERVAL>1, COUNT, UNTIL, BYMONTHDAY, BYSETPOS, etc. Keep family chores simple.
//
// Rule text is parsed case-insensitively ("freq=daily" == "FREQ=DAILY").
// The weekday of `date` is taken from the date's LOCAL components (the generator
// passes a date constructed for the target calendar day), using ISO weekday
// semantics (Mon..Sun) only as an internal mapping to BYDAY codes.
//
// IMPORTANT: the Edge Function (supabase/functions/generate-recurring-chores)
// ports this same logic into Deno (it cannot import this workspace TS package).
// If you change the supported subset here, update that copy too.

/** BYDAY two-letter codes, indexed by JS Date.getDay() (0=Sun..6=Sat). */
const DAY_CODES = ['SU', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA'] as const;

/**
 * Does a chore with `recurrenceRule` produce an occurrence on `date`?
 *
 * Returns false for null/empty rules (one-off chores) and for any rule outside
 * the supported subset documented above.
 */
export function occursOn(recurrenceRule: string | null, date: Date): boolean {
  if (recurrenceRule == null) return false;
  const rule = recurrenceRule.trim();
  if (rule.length === 0) return false;

  // Parse "KEY=VALUE;KEY=VALUE" into an upper-cased map.
  const parts = new Map<string, string>();
  for (const segment of rule.split(';')) {
    const eq = segment.indexOf('=');
    if (eq === -1) continue;
    const key = segment.slice(0, eq).trim().toUpperCase();
    const value = segment
      .slice(eq + 1)
      .trim()
      .toUpperCase();
    if (key.length > 0) parts.set(key, value);
  }

  const freq = parts.get('FREQ');
  if (freq === 'DAILY') return true;

  if (freq === 'WEEKLY') {
    const byday = parts.get('BYDAY');
    // WEEKLY with no BYDAY -> every day of the week.
    if (byday === undefined || byday.length === 0) return true;
    const wanted = byday
      .split(',')
      .map(d => d.trim())
      .filter(d => d.length > 0);
    // getDay() is always 0..6, so this index is always defined.
    const todayCode = DAY_CODES[date.getDay()] as string;
    return wanted.includes(todayCode);
  }

  // Unsupported FREQ or malformed rule -> do not generate.
  return false;
}
